//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAEE_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        public int Id { get; set; }
        public Nullable<int> Mesa { get; set; }
        public Nullable<int> Platos { get; set; }
    
        public virtual Mesa Mesa1 { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
