//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAEE_FINAL.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAEE_FINAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Command.
        /// </summary>
        public static string addCommand {
            get {
                return ResourceManager.GetString("addCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added correctly..
        /// </summary>
        public static string addCorrect {
            get {
                return ResourceManager.GetString("addCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Meal.
        /// </summary>
        public static string addMeal {
            get {
                return ResourceManager.GetString("addMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new table.
        /// </summary>
        public static string addTable {
            get {
                return ResourceManager.GetString("addTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete this element.
        /// </summary>
        public static string askDelete {
            get {
                return ResourceManager.GetString("askDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attention !.
        /// </summary>
        public static string attention {
            get {
                return ResourceManager.GetString("attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background :.
        /// </summary>
        public static string background {
            get {
                return ResourceManager.GetString("background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buttons.
        /// </summary>
        public static string buttons {
            get {
                return ResourceManager.GetString("buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colors.
        /// </summary>
        public static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Command.
        /// </summary>
        public static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Command.
        /// </summary>
        public static string commandEdit {
            get {
                return ResourceManager.GetString("commandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commands.
        /// </summary>
        public static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuration.
        /// </summary>
        public static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deleted correctly.
        /// </summary>
        public static string deleteCorrect {
            get {
                return ResourceManager.GetString("deleteCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diners.
        /// </summary>
        public static string diners {
            get {
                return ResourceManager.GetString("diners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dish.
        /// </summary>
        public static string dish {
            get {
                return ResourceManager.GetString("dish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dishes.
        /// </summary>
        public static string dishes {
            get {
                return ResourceManager.GetString("dishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edited correctly..
        /// </summary>
        public static string editCorrect {
            get {
                return ResourceManager.GetString("editCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error adding new element. Becouse: .
        /// </summary>
        public static string errorAdded {
            get {
                return ResourceManager.GetString("errorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error at delete element. Becouse: .
        /// </summary>
        public static string errorDelete {
            get {
                return ResourceManager.GetString("errorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error editing element. Becouse:.
        /// </summary>
        public static string errorEdited {
            get {
                return ResourceManager.GetString("errorEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foreground:.
        /// </summary>
        public static string foreground {
            get {
                return ResourceManager.GetString("foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French.
        /// </summary>
        public static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingredient.
        /// </summary>
        public static string ingredient {
            get {
                return ResourceManager.GetString("ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        public static string inventory {
            get {
                return ResourceManager.GetString("inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguages.
        /// </summary>
        public static string lenguages {
            get {
                return ResourceManager.GetString("lenguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meals.
        /// </summary>
        public static string meals {
            get {
                return ResourceManager.GetString("meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Meal.
        /// </summary>
        public static string mealsEdit {
            get {
                return ResourceManager.GetString("mealsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing data.
        /// </summary>
        public static string missingData {
            get {
                return ResourceManager.GetString("missingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        public static string modify {
            get {
                return ResourceManager.GetString("modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of table.
        /// </summary>
        public static string numberTable {
            get {
                return ResourceManager.GetString("numberTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We hope be usefull for the management  of your business.
        /// </summary>
        public static string subTitle2Home {
            get {
                return ResourceManager.GetString("subTitle2Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is the admin of your restaurant, here you can add and manage your tables, menus, inventorys and commands..
        /// </summary>
        public static string subTitleHome {
            get {
                return ResourceManager.GetString("subTitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        public static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tables.
        /// </summary>
        public static string tables {
            get {
                return ResourceManager.GetString("tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit table.
        /// </summary>
        public static string tablesEdit {
            get {
                return ResourceManager.GetString("tablesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tables.
        /// </summary>
        public static string tablesT {
            get {
                return ResourceManager.GetString("tablesT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texts.
        /// </summary>
        public static string texts {
            get {
                return ResourceManager.GetString("texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome!.
        /// </summary>
        public static string titleHome {
            get {
                return ResourceManager.GetString("titleHome", resourceCulture);
            }
        }
    }
}
